### PR TITLE
Fix enclosingCharacter  lost on component update

### PR DESCRIPTION
**Pull request by xqliu**
Fix enclosingCharacter  lost on component update,

the setting enclosingCharacter was reset to undefined upon component update, this PR address this issue and fix it.

### CODE REVIEW

**Comment by glinkot** [comment]
This is really needed, please pull this one in :)

**Comment by raedabusanad** [comment]
plz fix it!

**Comment by glinkot** [comment]
Yep, I've had to hack the code in node_modules which I feel bad about!

**Comment by raedabusanad** [comment]
What was the hack?

**Comment by glinkot** [comment]
Just look at the proposed change in the pull requests, and make the same
change.

**Comment by oliverbohnes** [comment]
The fix works very well here too.

**Comment by abdennour** [comment]
Already fixed with PR #263 
Use react-csv@2.1.7 at least

**Pull request closed without merging**
