### PR TITLE
Missing enclosingCharacter in Link.js

### LINKED ISSUE #191: I tried using this new enclosingCharacter prop but it does not seem to work.
I tried using this new enclosingCharacter prop but it does not seem to work.
I used it like explained in the README, that is with the following code:

<CSVLink data={csvData} separator=';' filename={csvName} enclosingCharacter={'}>
{/* my button */}
</CSVLink>

In the resulting downloaded CSV file, the enclosing characters are the default ones, that is double-quotes.

I read the files modified in this PR and everything seems OK.
Could someone tell me if I am using it the wrong way?

Thanks in advance 😊

### PR DESCRIPTION
**Pull request by mccabemj**
Fixes #191

### CODE REVIEW

**Comment by sg2231** [comment]
Hi, @mriccid. Do you have eta on this one?

Best regards

**Comment by mriccid** [comment]
> Hi, @mriccid. Do you have eta on this one?
> 
> Best regards

Hi @sg2231, I am no longer involved in maintaining this library. My apologies for not seeing this sooner and removing myself from the reviewers.

**Comment by abdennour** [comment]
Hi @mriccid , Thank you for contribution. the PR has conflict 

Hi @sg2231 , does this PR #263 solve your issue ? If so, you can upgrade to react-csv@2.1.7

**Comment by abdennour** [comment]
Fixed since longtime. 
use version 2.1.7 at least

**Pull request closed without merging**
