### PR TITLE
Escape double quotes in csv

### LINKED ISSUE #28: How to escape quotation marks in headers?
Say, I have this headers array:

```
let headers = ['Header 1', 'Header 2', 'Header "With Quotes" 3', 'Header 4'];
```

The third header's quotes will not be escaped, and the output will be:

```
"Header 1","Header 2","Header "With Quotes" 3", "Header 4"
```

Whereas the expected output is:

```
"Header 1","Header 2","Header ""With Quotes"" 3", "Header 4"
```

Reference: [RFC-4180](https://www.ietf.org/rfc/rfc4180.txt), part 7:

> If double-quotes are used to enclose fields, then a double-quote
       appearing inside a field must be escaped by preceding it with
       another double quote.  For example:
> "aaa","b""bb","ccc"

Is this feature implemented, and, if yes, how to use it?

### PR DESCRIPTION
**Pull request by clodal**
Related to #28 

- Enables react-csv to export html content e.g. `'<h1 style="text-align:center;">example</h1>'` by escaping double quotes as set out in [rfc4180](https://www.ietf.org/rfc/rfc4180.txt).

Look forward to your feedback. Thank you!

### CODE REVIEW

**Comment by verychgliu** [comment]
This PR would be useful for my current project.

**Comment by mccabemj** [comment]
@clodal can you fix the conflicting files so I can review for merge?

**Comment by dasniko** [comment]
I'd love to see this indeed very useful feature in react-csv, too.

Currently I do some character conversion/masking when collecting the data, but the cleaner solution would be to have this feature included in this lib.

**Comment by mriccid** [comment]
I'd prefer to modify `elementOrEmpty` to handle the escaping, as currently every cell's value goes through that function. It would be a smaller and simpler change.

**Comment by clodal** [comment]
@mriccid Thanks for the tip, works great!
@mccabemj Done, thank you

**Comment by mccabemj** [comment]
Do we think this is still needed with PR #74 in? If the prop `enclosingCharacter` was selected as a single quote, this would negate the need for it to be escaped (as per [rfc4180](https://www.ietf.org/rfc/rfc4180.txt))

>  If double-quotes are used to enclose fields, then a double-quote
       appearing inside a field must be escaped by preceding it with
       another double quote

Shall we conditionally look at the passed in `enclosingCharacter` or escape regardless? Thoughts @abdennour @mriccid @clodal ?

**Comment by clodal** [comment]
Alright, closing PR then! Thanks

**Pull request closed without merging**
