### PR TITLE
elementOrEmpty fix for 'false'

### LINKED ISSUE #145: Boolean 'false' value is blank in csv
Hi,

My JSON data has boolean fields. When the value is 'false' the CSV file has blank value for it. For 'true' value the CSV has correct data.

I believe this line could be the reason for this -> https://github.com/react-csv/react-csv/blob/master/src/core.js#L50

 Is there a work around for this? Thank you!

### PR DESCRIPTION
**Pull request by mccabemj**
Fixes #145

### CODE REVIEW

**Comment by asyriac** [comment]
@mccabemj Please merge this.

**Comment by asyriac** [comment]
@mriccid Please merge this

**Comment by rajank-intersection** [comment]
When we are planning to release it?

**Comment by richAtreides** [comment]
When will this be fixed? Its really annoying.

**Comment by chimichanga-dd** [comment]
still having issues with this one

**Comment by adsee42** [comment]
2.0.3 
`false` still show as empty string.

**Comment by angelo-martinez** [comment]
Still shows as empty string, Ive been getting around by turning the bool values into strings however fix would be greatly appreciated.

**Comment by chrismilnerlob** [comment]
Still showing as empty string. I converted the boolean value to a string which did solve the problem, however only temporarily as it has returned, please fix asap :)

**Comment by chrismilnerlob** [comment]
Still showing as an empty string, please fix, not functional until fixed, converting to string doesn't apply when connected to boolean api value

**Pull request merged**
