### PR TITLE
Update dependencies to resolve vulnerabilities

### PR DESCRIPTION
**Pull request by AdamLiechty**
`npm audit fix` was used to update these dev-dependencies to fix vulnerabilities.

Tests still pass.

### CODE REVIEW

**Comment by mccabemj** [comment]
@AdamLiechty where did `hoek` and `cryptiles` come from?

**Comment by AdamLiechty** [comment]
@mccabemj I've removed them.  They were previously subdependencies whose versions had vulnerabilities, but `npm ls` shows they are no longer used.

**Comment by grrowl** [comment]
In case it's of use to anyone, I've published #138, #137, #226, and #225 as `@mr-yum/react-csv@2.1.0`, the [repo is here](https://github.com/grrowl/react-csv)

**Comment by abdennour** [comment]
Thank you @AdamLiechty 
Github Dependabot is doing now the stuff.
I am gonna close this PR as it was implemented by Dependabot

**Pull request closed without merging**
