### PR TITLE
 Add typed definitions

### PR DESCRIPTION
**Pull request by marudy**
Add typed definitions generated from Microsoft/dts-gen. Then added manually prop types for `CSVLink` component.

### CODE REVIEW

**Comment by abdennour** [comment]
If someone is interested in being a contributor in this project, please let [contact me](http://in.abdennoor.com).

While it's hard to review all issues/PR due to time limitation, it is also not acceptable to approve PRs without review.

**Comment by mriccid** [comment]
Thanks for your contribution. I'm not too familiar with TypeScript, but it seems like the output from `dts-gen` should be used as the basis for the type definitions. How much more work would be required to complete these type definitions? My main concern is the number of `any`s in the types.

**Comment by mccabemj** [comment]
Agree with @mriccid. This seems like an output straight from dts-gen and needs work

**Comment by marudy** [comment]
Hi there @mriccid, @mccabemj,

sorry for the late reply. This typed definitions here are the result of `dts-gen` along with some customization so that TS compiler won't complain. At this stage it's not accurate but it could probably be used as basis. If someone would like to pick it up and continue feel free :) as my time is super limited during this period.

Cheers,
Tasos

**Pull request closed without merging**
