### PR TITLE
Use CSVLink to allow filename for CSVDownload 

### PR DESCRIPTION
**Pull request by Jarvis1010**
I just merged with the latest commits, I believe this should be correct now

### CODE REVIEW

**Comment by mccabemj** [comment]
@Jarvis1010 can you update this PR to fix/change failing unit tests and conflicts? I think it would be a good thing to get merged

**Comment by Jarvis1010** [comment]
Updated and CI working but coverage has decreased

**Comment by AdamLiechty** [comment]
@abdennour I have resolved the merge conflicts in this PR here: https://github.com/react-csv/react-csv/pull/129

**Comment by AdamLiechty** [comment]
#137 has these changes, along with fixes to unit tests, and without spurious style changes

**Pull request closed without merging**
