### PR TITLE
allow data from function on async onClick

### PR DESCRIPTION
**Pull request by dajomu**
Hi, I've added in the possibility to pass data as a function.
This means that if someone has an async onClick function they can handle data being downloaded, then call done().
This will allow the new data that has downloaded to propagate the csv data via a function that parses it.

### CODE REVIEW

**Comment by thomasmarr** [comment]
I agree this is an obvious use case. I hope this PR gets merged (sooner the better). @abdennour please do take a look at this - it would make the CSVLink component much more flexible.

@dajomu did you consider passing data as an argument the `done()` function instead of permitting an async function in the data prop. It should work either way, and there are pros and cons to both options, but personally I find something like this a little more readable:

```
onClick={async (event, done) => {
    const data = await fetchData()
    done(true, {data})
}}>
```

**Comment by jdileonardo** [comment]
This sort of functionality is exactly what i'm looking for right now lol. Thank you @dajomu 

ping @abdennour

**Comment by dajomu** [comment]
> I agree this is an obvious use case. I hope this PR gets merged (sooner the better). @abdennour please do take a look at this - it would make the CSVLink component much more flexible.
> 
> @dajomu did you consider passing data as an argument the `done()` function instead of permitting an async function in the data prop. It should work either way, and there are pros and cons to both options, but personally I find something like this a little more readable:
> 
> ```
> onClick={async (event, done) => {
>     const data = await fetchData()
>     done(true, {data})
> }}>
> ```

I agree, maybe I should have taken this approach. I can see benefits to both though.
At least with the way I did it you can just compose a function that you know will output the correct data response and that's all you have to think about.

The truth of the matter though is that the way I did it seems easier and took less time to code. My calculation was that the admin for this repo would be more likely to look at it and merge it if it was as simple as possible...

**Comment by thomasmarr** [comment]
@djomu :thumbsup:

@dajomu @jdileonardo I needed this functionality so I made a very simple function that does this and published to npm. Casting no shade on this project, but I needed a solution and wasn't able to wait for this PR to be merged. You can find it here: [use-csv-downloader](https://www.npmjs.com/package/use-csv-downloader)

**Comment by dajomu** [comment]
Yeah, tbh this project isn't really doing that much, it's not very difficult to roll your own csv code anyway.
If you were really pushed you could just nab the csv function from this code and include it in your codebase.

Googling a how to article brings up many very simple ways to do it -
https://code-maven.com/create-and-download-csv-with-javascript

**Comment by slorg1** [comment]
+1 :+1:

**Review by abdennour — CHANGES_REQUESTED** [review]
Please update README.md accordingly

**Comment by dajomu** [comment]
> Please update README.md accordingly
Hi, I've added a couple of examples to the readme

**Comment by ayush-shta** [comment]
I have made a fork of this repository in which you can call a function to download the CSV file anywhere you like without using a react component like in this package. This gives more flexibility to implement download CSV file logic and it has solved my similar problem as mentioned here.

Please check it out here: https://github.com/ayush-shta/download-csv

**Comment by TGChrisRArendt** [comment]
When is this getting merged? It's been 3 months and someone just has to click on the big green button...

**Comment by TGChrisRArendt** [comment]
> I have made a fork of this repository in which you can call a function to download the CSV file anywhere you like without using a react component like in this package. This gives more flexibility to implement download CSV file logic and it has solved my similar problem as mentioned here.
> 
> Please check it out here: https://github.com/ayush-shta/download-csv

Thanks so much for this! Exactly what I needed!

**Comment by abdennour** [comment]
Guys! i called for contribution.
@dajomu  please let me know if you are interested

**Comment by Ry-DS** [comment]
@dajomu since it doesn't seem the contributor is merging this any time soon, is it possible if you edit your repo to support the syntax `yarn add https://github.com/dajomu/react-csv.git` so we can still use this? This includes compiling the code and adding it to the `lib/` folder. Thank you!

**Comment by Ry-DS** [comment]
> I agree this is an obvious use case. I hope this PR gets merged (sooner the better). @abdennour please do take a look at this - it would make the CSVLink component much more flexible.
> 
> @dajomu did you consider passing data as an argument the `done()` function instead of permitting an async function in the data prop. It should work either way, and there are pros and cons to both options, but personally I find something like this a little more readable:
> 
> ```
> onClick={async (event, done) => {
>     const data = await fetchData()
>     done(true, {data})
> }}>
> ```

I agree with this approach, as right now we end up loading the data right when the component is mounted. It would be great if we could instead start the download when the button is clicked, so the user isn't left waiting unnecessarily.

**Comment by Rafael-Ramblas** [comment]
I'm don't know if is related, but i'm trying to use the async approach described in the readme and it gives me the error `done is not a function`

**Review by bnussman — APPROVED** [review]

**Comment by djomu** [comment]
Hello! Thanks for email, can you send me some attachments  of details.

**Comment by djomu** [comment]
Download WIN 11

https://pcguide4u.com/download-windows-11-iso/

**Comment by abdennour** [comment]
Seems like it's good feature. I am going to merge it
@dajomu @thomasmarr @jdileonardo @slorg1 @ayush-shta @TGChrisRArendt @Ry-DS @bnussman

BTW, we had now CICD pipeline for auto-release: as soon as, a new tag is pushed to master, the package will be released to npmjs.org

**Comment by abdennour** [comment]
Who can add unit tests for this great feature ? 
FYI @dajomu @thomasmarr @jdileonardo @slorg1 @ayush-shta @TGChrisRArendt @Ry-DS @bnussman
Then we can go

**Comment by abdennour** [comment]
Released with react-csv@2.1.8

**Comment by jtabone16** [comment]
Doesn't work...

https://github.com/react-csv/react-csv/issues/322

**Pull request merged**
