### PR TITLE
Add uFEFF support for IE11

### PR DESCRIPTION
**Pull request by bcfchen**
Updating Link.js to pass uFEFF param into new Blob when dealing with IE11

### CODE REVIEW

**Comment by bcfchen** [comment]
This is mainly based on https://github.com/react-csv/react-csv/pull/86. I simply resolved the merge conflict so this can be merged into the main repo faster

**Comment by bcfchen** [comment]
Any news on this? Could one of the admins merge this PR to make it part of the codebase?

**Comment by khumphrey** [comment]
@mccabemj You seem to have the ability to merge?

**Comment by khumphrey** [comment]
Or @abdennour 🙏

**Comment by bcfchen** [comment]
Or perhaps @mriccid? These changes have been there for quite a while, and there have been quite a lot of PRs for this repo too.

**Comment by mccabemj** [comment]
This has now been implemented in v1.1.2 through another PR. Thank you for your contribution @bcfchen

**Pull request closed without merging**
