### PR TITLE
Rename Link.js to Link.jsx

### PR DESCRIPTION
**Pull request by gla23**
I'm switching a project to [Vite](https://vitejs.dev/) and it needs the filename to match the content. This fork fixes a hurdle we couldn't get over otherwise, and I thought it may be useful for others to get the fix.

There doesn't seem to be any downside as build tools look for jsx files anyway.

### CODE REVIEW

**Comment by gla23** [comment]
If others want to use my fork before this gets merged in, it works for me to put the following in my package.json:
```
"react-csv": "git://github.com/gla23/react-csv.git",
```

**Review by mriccid — APPROVED** [review]

**Comment by mriccid** [comment]
@abdennour I have approved this but it's been a long time since I've published a release for this package. Are you able to merge this and publish the change to NPM?

**Comment by abdennour** [comment]
Hello @mriccid , happy to hear from you after long time.

Actually there is now CICD. Just merge to master and push new git tag and the publish will be done using that tag as npm package version

**Comment by mriccid** [comment]
`react-csv@2.2.2` has been published which contains this fix

**Pull request merged**
