### PR TITLE
Fix deprecated componentWillReceiveProps warning

### LINKED ISSUE #182: React upgrading
Will the lib get a release soon on React version?
16.+ apps don't support `componentWillReceiveProps`

### PR DESCRIPTION
**Pull request by kartouch**
Fixes #182

### CODE REVIEW

**Comment by cefeboru** [comment]
Waiting for this fix 😬

**Comment by mungojam** [comment]
looks like all the approvals are in, so can it be merged?

**Comment by minotogna** [comment]
any news on this?

**Comment by anthonyelliott-pillar** [comment]
This would be great to get merged in!!! We're seeing lots of console warnings from this.

**Comment by anthonyelliott-pillar** [comment]
@abdennour @mccabemj - can one of you merge this small PR in? It would be a great help!

**Comment by anthonyelliott-pillar** [comment]
thanks for merging @abdennour!

**Comment by abdennour** [comment]
I am releasing @anthonyelliott-pillar  . Please stay tuned! Otherwise, point your app to react-csv 2.0.1 🎉

**Comment by abdennour** [comment]
Fixed in release [2.0.1](https://github.com/react-csv/react-csv/releases/tag/v2.0.1)

**Pull request merged**
