### PR TITLE
adding check for null header

### PR DESCRIPTION
**Pull request by tegranjeet**

### CODE REVIEW

**Comment by tegranjeet** [comment]
fixes error when using nested dot notation header keys

**Comment by tegranjeet** [comment]
address issue #180

**Comment by nandishvas** [comment]
Facing same issue for null values when using nested json with dot notation

**Comment by tegranjeet** [comment]
@abdennour any chance of getting eyes on this?

Thanks

**Comment by developervini** [comment]
up

**Comment by renelizarraga** [comment]
approve this please

**Comment by jonnyn** [comment]
up

**Comment by developervini** [comment]
up

**Comment by jimmymorris** [comment]
+1

**Comment by abdennour** [comment]
there was a conflict. I have fixed.

**Comment by abdennour** [comment]
Merged! Available since react-csv@2.1.9

PFYI @tegranjeet @nandishvas @developervini @renelizarraga @jonnyn @jimmymorris

**Pull request merged**
