### PR TITLE
Fix for checking change in props

### PR DESCRIPTION
**Pull request by ttrzeng**
Fixes for issue: 
No update when data prop changes #115

### CODE REVIEW

**Comment by mccabemj** [comment]
@ttrzeng thanks for this. Can you please generate the bundle to go along with this PR as per the docs. I can then get it merged

**Comment by ttrzeng** [comment]
@mccabemj I have bundled and generated ran npm run docgen. Let me know if you need anything else. :D

**Comment by tomaszrondio** [comment]
big thank you for this fix. It is a dealbreaker for me

**Comment by smblee** [comment]
The only thing about this is the componentWillReceiveProps is deprecated in React 16. But seeing this package supports 15.4 I guess this should be fine?

**Comment by hijackthegit** [comment]
> The only thing about this is the `componentWillReceiveProps` is deprecated in React 16. But seeing this package supports 15.4 I guess this should be fine?

It is not deprecated but marked as 'unsafe' warning in react 16, the react roadmap will deprecate this in react 17. As react-csv is still using react 15 so it is safe.

**Comment by FarazPatankar** [comment]
Can we get this merged or are there any issues with this PR?

**Comment by ttrzeng** [comment]
@mccabemj bump

**Comment by tomaszrondio** [comment]
bump bump

**Comment by mccabemj** [comment]
Sorry for the delay on this everyone. Will review and merge in the morning

**Pull request merged**
