### PR TITLE
Update handle legacy (IE 11) - ufeff and use props instead of passed in values

### PR DESCRIPTION
**Pull request by khumphrey**
#### Summary of Changes
- Update handle legacy to include ufeff (see https://github.com/react-csv/react-csv/pull/151 for more details)
- Update handle legacy to use props rather than passed in values. This solves the problem of out of date data when using asyncOnClick
- Added unit tests for handleLegacy

This resolves the following issues:
- https://github.com/react-csv/react-csv/issues/60
- https://github.com/react-csv/react-csv/issues/141

@abdennour @mccabemj you are the two that I noted have the ability to merge soooo... 🙏 😄 

My team would love to continue using this, but without these changes ASAP we are going to have to figure something else out 😢

### CODE REVIEW

**Comment by khumphrey** [comment]
Also maybe @rkdmen since I saw you approve another one

**Comment by khumphrey** [comment]
image
😄

**Comment by mccabemj** [comment]
Code looks good to me, and I understand this is important for you @khumphrey 

@abdennour do you have time to get this in today? If not, I can spare some time this evening

**Comment by abdennour** [comment]
@mccabemj please go ahead. I am super busy this week.

**Pull request merged**
