### PR TITLE
renamed Link.js to Link.jsx

### PR DESCRIPTION
**Pull request by matzeso**
This would resolve compilation with Vite.
There is already an existing issue here: https://github.com/react-csv/react-csv/issues/268

I fixed the core.js part to check whether tests would still run fine, but removed it for this commit as there is already a separate PR and I did not want to interfere. 

`npm run test` and `npm run compile` works fine.

### CODE REVIEW

**Comment by matthewdavi** [comment]
This would be a nice help

**Comment by dereck-rasmussen** [comment]
Same here, we are using Vite and this issue is preventing us from being able to use this library.

**Comment by cyapa** [comment]
Any idea when this may get merged?

**Comment by matzeso** [comment]
I would propose you fork my version for yourself and then add the library directly through github.
As this has not been implemented for half a year, you will probably also not get any other updates on this anyway.

https://github.com/matzeso/react-csv

```
// or your forked link 
npm i git+https://github.com/matzeso/react-csv.git
```

**Comment by atefBB** [comment]
@abdennour Bro, any chance to merge this?

**Comment by abdennour** [comment]
Yes @atefBB  ! There is chance

**Comment by abdennour** [comment]
Great @matzeso !

**Comment by abdennour** [comment]
CI is failing https://github.com/react-csv/react-csv/runs/4577026326?check_suite_focus=true
I am gonna revert back @matzeso

**Pull request merged**
